// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: imageboard/imageboard.proto

package imageboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DiskcacheEnabled bool                   `protobuf:"varint,2,opt,name=diskcache_enabled,json=diskcacheEnabled,proto3" json:"diskcache_enabled,omitempty"`
	MemcacheEnabled  bool                   `protobuf:"varint,3,opt,name=memcache_enabled,json=memcacheEnabled,proto3" json:"memcache_enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_imageboard_imageboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_imageboard_imageboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_imageboard_imageboard_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Status) GetDiskcacheEnabled() bool {
	if x != nil {
		return x.DiskcacheEnabled
	}
	return false
}

func (x *Status) GetMemcacheEnabled() bool {
	if x != nil {
		return x.MemcacheEnabled
	}
	return false
}

type SetStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusReq) Reset() {
	*x = SetStatusReq{}
	mi := &file_imageboard_imageboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusReq) ProtoMessage() {}

func (x *SetStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_imageboard_imageboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusReq.ProtoReflect.Descriptor instead.
func (*SetStatusReq) Descriptor() ([]byte, []int) {
	return file_imageboard_imageboard_proto_rawDescGZIP(), []int{1}
}

func (x *SetStatusReq) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type StatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_imageboard_imageboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_imageboard_imageboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_imageboard_imageboard_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResp) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type JumpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JumpReq) Reset() {
	*x = JumpReq{}
	mi := &file_imageboard_imageboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JumpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JumpReq) ProtoMessage() {}

func (x *JumpReq) ProtoReflect() protoreflect.Message {
	mi := &file_imageboard_imageboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JumpReq.ProtoReflect.Descriptor instead.
func (*JumpReq) Descriptor() ([]byte, []int) {
	return file_imageboard_imageboard_proto_rawDescGZIP(), []int{3}
}

func (x *JumpReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_imageboard_imageboard_proto protoreflect.FileDescriptor

const file_imageboard_imageboard_proto_rawDesc = "" +
	"\n" +
	"\x1bimageboard/imageboard.proto\x12\rimageboard.v1\x1a\x1bgoogle/protobuf/empty.proto\"z\n" +
	"\x06Status\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12+\n" +
	"\x11diskcache_enabled\x18\x02 \x01(\bR\x10diskcacheEnabled\x12)\n" +
	"\x10memcache_enabled\x18\x03 \x01(\bR\x0fmemcacheEnabled\"=\n" +
	"\fSetStatusReq\x12-\n" +
	"\x06status\x18\x01 \x01(\v2\x15.imageboard.v1.StatusR\x06status\";\n" +
	"\n" +
	"StatusResp\x12-\n" +
	"\x06status\x18\x01 \x01(\v2\x15.imageboard.v1.StatusR\x06status\"\x1d\n" +
	"\aJumpReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xc6\x01\n" +
	"\n" +
	"ImageBoard\x12@\n" +
	"\tSetStatus\x12\x1b.imageboard.v1.SetStatusReq\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x19.imageboard.v1.StatusResp\x126\n" +
	"\x04Jump\x12\x16.imageboard.v1.JumpReq\x1a\x16.google.protobuf.EmptyB?Z=github.com/parandandrd/sportsmatrix/internal/proto/imageboardb\x06proto3"

var (
	file_imageboard_imageboard_proto_rawDescOnce sync.Once
	file_imageboard_imageboard_proto_rawDescData []byte
)

func file_imageboard_imageboard_proto_rawDescGZIP() []byte {
	file_imageboard_imageboard_proto_rawDescOnce.Do(func() {
		file_imageboard_imageboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imageboard_imageboard_proto_rawDesc), len(file_imageboard_imageboard_proto_rawDesc)))
	})
	return file_imageboard_imageboard_proto_rawDescData
}

var file_imageboard_imageboard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_imageboard_imageboard_proto_goTypes = []any{
	(*Status)(nil),        // 0: imageboard.v1.Status
	(*SetStatusReq)(nil),  // 1: imageboard.v1.SetStatusReq
	(*StatusResp)(nil),    // 2: imageboard.v1.StatusResp
	(*JumpReq)(nil),       // 3: imageboard.v1.JumpReq
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_imageboard_imageboard_proto_depIdxs = []int32{
	0, // 0: imageboard.v1.SetStatusReq.status:type_name -> imageboard.v1.Status
	0, // 1: imageboard.v1.StatusResp.status:type_name -> imageboard.v1.Status
	1, // 2: imageboard.v1.ImageBoard.SetStatus:input_type -> imageboard.v1.SetStatusReq
	4, // 3: imageboard.v1.ImageBoard.GetStatus:input_type -> google.protobuf.Empty
	3, // 4: imageboard.v1.ImageBoard.Jump:input_type -> imageboard.v1.JumpReq
	4, // 5: imageboard.v1.ImageBoard.SetStatus:output_type -> google.protobuf.Empty
	2, // 6: imageboard.v1.ImageBoard.GetStatus:output_type -> imageboard.v1.StatusResp
	4, // 7: imageboard.v1.ImageBoard.Jump:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_imageboard_imageboard_proto_init() }
func file_imageboard_imageboard_proto_init() {
	if File_imageboard_imageboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imageboard_imageboard_proto_rawDesc), len(file_imageboard_imageboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imageboard_imageboard_proto_goTypes,
		DependencyIndexes: file_imageboard_imageboard_proto_depIdxs,
		MessageInfos:      file_imageboard_imageboard_proto_msgTypes,
	}.Build()
	File_imageboard_imageboard_proto = out.File
	file_imageboard_imageboard_proto_goTypes = nil
	file_imageboard_imageboard_proto_depIdxs = nil
}
