// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sportboard/sportboard.proto

package sportboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Enabled           bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	FavoriteHidden    bool                   `protobuf:"varint,2,opt,name=favorite_hidden,json=favoriteHidden,proto3" json:"favorite_hidden,omitempty"`
	FavoriteSticky    bool                   `protobuf:"varint,3,opt,name=favorite_sticky,json=favoriteSticky,proto3" json:"favorite_sticky,omitempty"`
	RecordRankEnabled bool                   `protobuf:"varint,4,opt,name=record_rank_enabled,json=recordRankEnabled,proto3" json:"record_rank_enabled,omitempty"`
	UseGradient       bool                   `protobuf:"varint,5,opt,name=use_gradient,json=useGradient,proto3" json:"use_gradient,omitempty"`
	LiveOnly          bool                   `protobuf:"varint,6,opt,name=live_only,json=liveOnly,proto3" json:"live_only,omitempty"`
	DetailedLive      bool                   `protobuf:"varint,7,opt,name=detailed_live,json=detailedLive,proto3" json:"detailed_live,omitempty"`
	ShowLeagueLogo    bool                   `protobuf:"varint,8,opt,name=show_league_logo,json=showLeagueLogo,proto3" json:"show_league_logo,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_sportboard_sportboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_sportboard_sportboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_sportboard_sportboard_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Status) GetFavoriteHidden() bool {
	if x != nil {
		return x.FavoriteHidden
	}
	return false
}

func (x *Status) GetFavoriteSticky() bool {
	if x != nil {
		return x.FavoriteSticky
	}
	return false
}

func (x *Status) GetRecordRankEnabled() bool {
	if x != nil {
		return x.RecordRankEnabled
	}
	return false
}

func (x *Status) GetUseGradient() bool {
	if x != nil {
		return x.UseGradient
	}
	return false
}

func (x *Status) GetLiveOnly() bool {
	if x != nil {
		return x.LiveOnly
	}
	return false
}

func (x *Status) GetDetailedLive() bool {
	if x != nil {
		return x.DetailedLive
	}
	return false
}

func (x *Status) GetShowLeagueLogo() bool {
	if x != nil {
		return x.ShowLeagueLogo
	}
	return false
}

type SetStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusReq) Reset() {
	*x = SetStatusReq{}
	mi := &file_sportboard_sportboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusReq) ProtoMessage() {}

func (x *SetStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_sportboard_sportboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusReq.ProtoReflect.Descriptor instead.
func (*SetStatusReq) Descriptor() ([]byte, []int) {
	return file_sportboard_sportboard_proto_rawDescGZIP(), []int{1}
}

func (x *SetStatusReq) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type StatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_sportboard_sportboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_sportboard_sportboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_sportboard_sportboard_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResp) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_sportboard_sportboard_proto protoreflect.FileDescriptor

const file_sportboard_sportboard_proto_rawDesc = "" +
	"\n" +
	"\x1bsportboard/sportboard.proto\x12\bsport.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xb3\x02\n" +
	"\x06Status\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12'\n" +
	"\x0ffavorite_hidden\x18\x02 \x01(\bR\x0efavoriteHidden\x12'\n" +
	"\x0ffavorite_sticky\x18\x03 \x01(\bR\x0efavoriteSticky\x12.\n" +
	"\x13record_rank_enabled\x18\x04 \x01(\bR\x11recordRankEnabled\x12!\n" +
	"\fuse_gradient\x18\x05 \x01(\bR\vuseGradient\x12\x1b\n" +
	"\tlive_only\x18\x06 \x01(\bR\bliveOnly\x12#\n" +
	"\rdetailed_live\x18\a \x01(\bR\fdetailedLive\x12(\n" +
	"\x10show_league_logo\x18\b \x01(\bR\x0eshowLeagueLogo\"8\n" +
	"\fSetStatusReq\x12(\n" +
	"\x06status\x18\x01 \x01(\v2\x10.sport.v1.StatusR\x06status\"6\n" +
	"\n" +
	"StatusResp\x12(\n" +
	"\x06status\x18\x01 \x01(\v2\x10.sport.v1.StatusR\x06status2\x7f\n" +
	"\x05Sport\x12;\n" +
	"\tSetStatus\x12\x16.sport.v1.SetStatusReq\x1a\x16.google.protobuf.Empty\x129\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x14.sport.v1.StatusRespB?Z=github.com/parandandrd/sportsmatrix/internal/proto/sportboardb\x06proto3"

var (
	file_sportboard_sportboard_proto_rawDescOnce sync.Once
	file_sportboard_sportboard_proto_rawDescData []byte
)

func file_sportboard_sportboard_proto_rawDescGZIP() []byte {
	file_sportboard_sportboard_proto_rawDescOnce.Do(func() {
		file_sportboard_sportboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sportboard_sportboard_proto_rawDesc), len(file_sportboard_sportboard_proto_rawDesc)))
	})
	return file_sportboard_sportboard_proto_rawDescData
}

var file_sportboard_sportboard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sportboard_sportboard_proto_goTypes = []any{
	(*Status)(nil),        // 0: sport.v1.Status
	(*SetStatusReq)(nil),  // 1: sport.v1.SetStatusReq
	(*StatusResp)(nil),    // 2: sport.v1.StatusResp
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_sportboard_sportboard_proto_depIdxs = []int32{
	0, // 0: sport.v1.SetStatusReq.status:type_name -> sport.v1.Status
	0, // 1: sport.v1.StatusResp.status:type_name -> sport.v1.Status
	1, // 2: sport.v1.Sport.SetStatus:input_type -> sport.v1.SetStatusReq
	3, // 3: sport.v1.Sport.GetStatus:input_type -> google.protobuf.Empty
	3, // 4: sport.v1.Sport.SetStatus:output_type -> google.protobuf.Empty
	2, // 5: sport.v1.Sport.GetStatus:output_type -> sport.v1.StatusResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sportboard_sportboard_proto_init() }
func file_sportboard_sportboard_proto_init() {
	if File_sportboard_sportboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sportboard_sportboard_proto_rawDesc), len(file_sportboard_sportboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sportboard_sportboard_proto_goTypes,
		DependencyIndexes: file_sportboard_sportboard_proto_depIdxs,
		MessageInfos:      file_sportboard_sportboard_proto_msgTypes,
	}.Build()
	File_sportboard_sportboard_proto = out.File
	file_sportboard_sportboard_proto_goTypes = nil
	file_sportboard_sportboard_proto_depIdxs = nil
}
