// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: basicboard/basicboard.proto

package basicboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_basicboard_basicboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_basicboard_basicboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_basicboard_basicboard_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusReq) Reset() {
	*x = SetStatusReq{}
	mi := &file_basicboard_basicboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusReq) ProtoMessage() {}

func (x *SetStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_basicboard_basicboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusReq.ProtoReflect.Descriptor instead.
func (*SetStatusReq) Descriptor() ([]byte, []int) {
	return file_basicboard_basicboard_proto_rawDescGZIP(), []int{1}
}

func (x *SetStatusReq) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type StatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_basicboard_basicboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_basicboard_basicboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_basicboard_basicboard_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResp) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_basicboard_basicboard_proto protoreflect.FileDescriptor

const file_basicboard_basicboard_proto_rawDesc = "" +
	"\n" +
	"\x1bbasicboard/basicboard.proto\x12\bboard.v1\x1a\x1bgoogle/protobuf/empty.proto\"\"\n" +
	"\x06Status\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"8\n" +
	"\fSetStatusReq\x12(\n" +
	"\x06status\x18\x01 \x01(\v2\x10.board.v1.StatusR\x06status\"6\n" +
	"\n" +
	"StatusResp\x12(\n" +
	"\x06status\x18\x01 \x01(\v2\x10.board.v1.StatusR\x06status2\x84\x01\n" +
	"\n" +
	"BasicBoard\x12;\n" +
	"\tSetStatus\x12\x16.board.v1.SetStatusReq\x1a\x16.google.protobuf.Empty\x129\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x14.board.v1.StatusRespB?Z=github.com/parandandrd/sportsmatrix/internal/proto/basicboardb\x06proto3"

var (
	file_basicboard_basicboard_proto_rawDescOnce sync.Once
	file_basicboard_basicboard_proto_rawDescData []byte
)

func file_basicboard_basicboard_proto_rawDescGZIP() []byte {
	file_basicboard_basicboard_proto_rawDescOnce.Do(func() {
		file_basicboard_basicboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basicboard_basicboard_proto_rawDesc), len(file_basicboard_basicboard_proto_rawDesc)))
	})
	return file_basicboard_basicboard_proto_rawDescData
}

var file_basicboard_basicboard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_basicboard_basicboard_proto_goTypes = []any{
	(*Status)(nil),        // 0: board.v1.Status
	(*SetStatusReq)(nil),  // 1: board.v1.SetStatusReq
	(*StatusResp)(nil),    // 2: board.v1.StatusResp
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_basicboard_basicboard_proto_depIdxs = []int32{
	0, // 0: board.v1.SetStatusReq.status:type_name -> board.v1.Status
	0, // 1: board.v1.StatusResp.status:type_name -> board.v1.Status
	1, // 2: board.v1.BasicBoard.SetStatus:input_type -> board.v1.SetStatusReq
	3, // 3: board.v1.BasicBoard.GetStatus:input_type -> google.protobuf.Empty
	3, // 4: board.v1.BasicBoard.SetStatus:output_type -> google.protobuf.Empty
	2, // 5: board.v1.BasicBoard.GetStatus:output_type -> board.v1.StatusResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_basicboard_basicboard_proto_init() }
func file_basicboard_basicboard_proto_init() {
	if File_basicboard_basicboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basicboard_basicboard_proto_rawDesc), len(file_basicboard_basicboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basicboard_basicboard_proto_goTypes,
		DependencyIndexes: file_basicboard_basicboard_proto_depIdxs,
		MessageInfos:      file_basicboard_basicboard_proto_msgTypes,
	}.Build()
	File_basicboard_basicboard_proto = out.File
	file_basicboard_basicboard_proto_goTypes = nil
	file_basicboard_basicboard_proto_depIdxs = nil
}
