#!/bin/bash
set -euo pipefail

ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"
DOCKERCONF="${ROOT}/.dockerconfig"
GO_VERSION="1.25.3"

getsha() {
  if uname -s | grep -i darwin &> /dev/null; then
    shasum -a 256 "${1}" | awk '{print $1}'
  else
    sha256sum "${1}" | awk '{print $1}'
  fi
}

latestpibuilder() {
  arch="$1"
  buildos="${2:-bullseye}"
  case "${arch}" in
    amd64|x86_64)
      arch=amd64
      ;;
    arm64)
      arch=aarch64
      ;;
    *)
    ;;
  esac
  echo "robbydyer/pibuilder-${arch}-${buildos}:$(getsha "${ROOT}/Dockerfile.pibuilder")"
}

latestlinter() {
  echo "robbydyer/rgbmatrixlint:$(getsha "${ROOT}/Dockerfile.lint")"
}

dockerlogin() {
  if [ -d "${DOCKERCONF}" ]; then
    return
  fi
  echo "Enter docker hub credentials:"
  echo "${DOCKERHUB_PASS}" | docker --config="${DOCKERCONF}" login -u robbydyer --password-stdin
}

install_go() {
  if go version | grep "${GO_VERSION}"; then
    return
  fi

  if [ ! -d /usr/local/go ]; then
    mkdir -p /usr/local/go
  fi

  case "$(uname -m)" in
  aarch64)
    f="go${GO_VERSION}.linux-arm64.tar.gz"
    ;;
  armv7l|armv6l)
    f="go${GO_VERSION}.linux-armv6l.tar.gz"
    ;;
  esac

  echo "=> Installing Go from https://golang.org/dl/${f}"
  wget "https://golang.org/dl/${f}"
  sudo rm -rf /usr/local/go/*
  sudo tar -C /usr/local -xzf "${f}"
  rm -f "${f}"
}
