#!/bin/bash
set -eou pipefail

ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"
cd "${ROOT}"

[ ! -d "${ROOT}/docs-base" ] && mkdir "${ROOT}/docs-base"

for full in $(find proto -name '*.proto' | sort | uniq); do
  dir="$(dirname "${full}")"
  cd "${dir}"
  basefile="$(basename "${full}")"
  base="$(echo "${basefile}" | cut -f1 -d.)"
  set -x
  go run github.com/go-bridget/twirp-swagger-gen/cmd/twirp-swagger-gen \
    -in "${basefile}" \
    -out "${ROOT}/docs-base/${base}.swagger.json" \
    -host localhost:8080 \
    -pathPrefix ""
  cd "${ROOT}"
done

# gsed on macOS, plain sed everywhere else
SED="$(command -v gsed || command -v sed)"

src="${ROOT}/web/src/matrix.swagger.json"
cat "${ROOT}"/docs-base/* | jq -s 'reduce .[] as $item ({}; . * $item)' > "${src}"

"${SED}" -i 's,/twirp/matrix.v1.Sportsmatrix,/matrix.v1.Sportsmatrix,g' "${src}"
"${SED}" -i 's,/twirp/board.v1.BasicBoard,/stocks/board.v1.BasicBoard,g' "${src}"
"${SED}" -i 's,/twirp/racing.v1.Racing,/f1/racing.v1.Racing,g' "${src}"
"${SED}" -i 's,"title": "weatherboard.proto","title": "Sportsmatrix API",g' "${src}"
"${SED}" -i 's,/twirp/imageboard,/imageboard,g' "${src}"
"${SED}" -i 's,/twirp/sport.v1,/nhl/sport.v1,g' "${src}"
"${SED}" -i 's,/twirp/weather,/weather,g' "${src}"
"${SED}" -i 's/"BasicBoard"/"BasicBoard - includes stocks, pga, clock, sys"/g' "${src}"
"${SED}" -i 's/"Sport"/"Sport - nhl, mlb, nfl, ncaaf, ncaam, epl, mls, nba, ncaaw, wnba, ligue, seriea, laliga"/g' "${src}"
